---
bootstrap_ntp: false

timezone: "Etc/UTC"
ntp_servers:
  - time.google.com
  - time.cloudflare.com
ntp_fallback_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
ntp_root_distance_max_sec: 5
ntp_poll_interval_min_sec: 32
ntp_poll_interval_max_sec: 2048
